### ISSUE TITLE
Fix importlib-resources in 3.5.0-3.5.3 - [merged]

### ISSUE THREAD

**Issue by jaraco** [python/importlib_resources#178]
In GitLab by @asottile on Mar 2, 2020, 15:50

_Merges py35_compat -> master_

Resolves #83

This uses [flake8-typing-imports](https://github.com/asottile/flake8-typing-imports) to validate 3.5.0-3.5.3

I did the `tox.ini` patch first which resulted in this failure:

```
importlib_resources/_py3.py:13:1: TYP001 guard import by `if False:  # TYPE_CHECKING`: ContextManager (not in 3.5.0, 3.5.1, 3.5.2, 3.5.3)
```

I then fixed that and it now passes

___

without this patch, this fails like:

```
[2020-03-02T20:39:18Z] Traceback (most recent call last):
[2020-03-02T20:39:18Z]   File "/usr/local/bin/pre-commit", line 5, in <module>
[2020-03-02T20:39:18Z]     from pre_commit.main import main
[2020-03-02T20:39:18Z]   File "/usr/local/lib/python3.5/dist-packages/pre_commit/main.py", line 11, in <module>
[2020-03-02T20:39:18Z]     from pre_commit import git
[2020-03-02T20:39:18Z]   File "/usr/local/lib/python3.5/dist-packages/pre_commit/git.py", line 7, in <module>
[2020-03-02T20:39:18Z]     from pre_commit.util import cmd_output
[2020-03-02T20:39:18Z]   File "/usr/local/lib/python3.5/dist-packages/pre_commit/util.py", line 21, in <module>
[2020-03-02T20:39:18Z]     from importlib_resources import open_binary
[2020-03-02T20:39:18Z]   File "/usr/local/lib/python3.5/dist-packages/importlib_resources/__init__.py", line 22, in <module>
[2020-03-02T20:39:18Z]     from importlib_resources._py3 import (
[2020-03-02T20:39:18Z]   File "/usr/local/lib/python3.5/dist-packages/importlib_resources/_py3.py", line 13, in <module>
[2020-03-02T20:39:18Z]     from typing import ContextManager
[2020-03-02T20:39:18Z] ImportError: cannot import name 'ContextManager'
```

**Comment by jaraco** [comment]
In GitLab by @asottile on Mar 2, 2020, 15:52

changed the description

**Comment by jaraco** [comment]
In GitLab by @jaraco on Mar 2, 2020, 17:22

mentioned in merge request !91

**Comment by jaraco** [comment]
In GitLab by @jaraco on Mar 2, 2020, 17:26

Thanks so much for this Anthony and especially for creating flake8-typing-imports. I had no idea the typing module was so unstable, and I learned a lot from the readme on the flake8-typing-imports project.

What do you think instead about !91, which avoids the `if False` and `# TYPE_CHECKING`?

**Comment by jaraco** [comment]
In GitLab by @asottile on Mar 2, 2020, 17:32

!91 looks like I should improve `flake8-typing-imports` hehehe -- that'll crash with an `AttributeError`:

```console
$ ./python
Python 3.5.3 (default, Mar  2 2020, 14:31:06) 
[GCC 7.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import typing
>>> def f() -> typing.ContextManager: ...
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'typing' has no attribute 'ContextManager'
```

**Comment by jaraco** [comment]
In GitLab by @jaraco on Mar 2, 2020, 17:37

Oh, interesting! What about `'typing.ContextManager'`?

**Comment by jaraco** [comment]
In GitLab by @asottile on Mar 2, 2020, 17:42

that would work and is what I'm working on making flake8-typing-imports suggest in that situation

it's admittedly a little bit weird (I haven't seen anyone type anything using that approach), this PR is what I've seen as "the approach" (note that the comment isn't functional, just if 3.5.4 were the minimum version I'd use `from typing import TYPE_CHECKING` and then `if TYPE_CHECKING`)

**Comment by jaraco** [comment]
In GitLab by @jaraco on Mar 2, 2020, 17:46

Cool. Since that's what you're suggesting in (a future version of) the tool, let's go with the other PR.

**Comment by jaraco** [comment]
In GitLab by @jaraco on Mar 2, 2020, 17:46

closed

**Comment by jaraco** [comment]
In GitLab by @asottile on Mar 2, 2020, 17:50

oh uh, I would have merged this one -- I've never seen anyone write typed code in the style that !91 does

**Comment by jaraco** [comment]
In GitLab by @asottile on Mar 2, 2020, 17:51

that is, this PR is the idiomatic approach for this situation

**Comment by jaraco** [comment]
In GitLab by @jaraco on Mar 2, 2020, 18:09

I see. I'll merge it then.

**Comment by jaraco** [comment]
In GitLab by @jaraco on Mar 2, 2020, 18:09

reopened

**Comment by jaraco** [comment]
In GitLab by @jaraco on Mar 2, 2020, 18:11

mentioned in commit 06a49860884029d0381e497e700b773fadef5f77

**Comment by jaraco** [comment]
In GitLab by @jaraco on Mar 2, 2020, 18:11

merged

**Comment by jaraco** [comment]
In GitLab by @lukaszdudek-silvair on Mar 4, 2020, 03:12

Great work @asottile! When can we expect this gets released?

**Comment by jaraco** [comment]
In GitLab by @asottile on Mar 4, 2020, 09:23

I believe it already is in v1.2.0

**Comment by jaraco** [comment]
In GitLab by @jaraco on Mar 8, 2020, 20:08

[Confirmed](https://importlib-resources.readthedocs.io/en/latest/changelog%20(links).html#v1-2-0).
