### ISSUE TITLE
[5.2.0] importlib_resources.path does not throw FileNotFoundError anymore

### ISSUE THREAD

**Issue by chaen** [python/importlib_resources#230]
Hi,
the release `5.2.0` introduced quite a big change, and I am not sure it was expected/wanted.

Consider this simple file

```python
import importlib_resources
importlib_resources.path('attr', 'toto.py')
print("OK")
```

Obviously, `toto.py` does not exist. 

With `5.1.4`, we get

```
Traceback (most recent call last):                                                                                                                                                            
  File "/tmp/test_import.py", line 2, in <module>                                                                                                                                             
    importlib_resources.path('attr', 'toto.py')                                                                                                                                               
  File "/home/chaen/miniconda2/envs/test-env-debug/lib/python3.9/site-packages/importlib_resources/_py3.py", line 104, in path                                                                
    _path_from_reader(reader, _common.normalize_path(resource))                                                                                                                               
  File "/home/chaen/miniconda2/envs/test-env-debug/lib/python3.9/site-packages/importlib_resources/_py3.py", line 113, in _path_from_reader                                                   
    return _path_from_resource_path(reader, resource) or _path_from_open_resource(                                                                                                            
  File "/home/chaen/miniconda2/envs/test-env-debug/lib/python3.9/site-packages/importlib_resources/_py3.py", line 124, in _path_from_open_resource                                            
    saved = io.BytesIO(reader.open_resource(resource).read())                                                                                                                                 
  File "<frozen importlib._bootstrap_external>", line 1060, in open_resource                                                                                                                  
FileNotFoundError: [Errno 2] No such file or directory: '/home/chaen/miniconda2/envs/test-env-debug/lib/python3.9/site-packages/attr/toto.py'       
```

While with 5.2.0, it just goes through.

Is that a desired change ?

**Comment by FFY00** [comment]
Yes. The exception will now happen when trying to read the file.

**Comment by chaen** [comment]
OK. I guess I failed at understanding that from the changelog. But if it is expected, all good, I can close the issue :-)

**Comment by FFY00** [comment]
Yeah, it is due to the legacy API now being on top of the new `files()` API.

I would recommend you to switch to the new API:

```python
import importlib_resources

toto = importlib_resources.files('attr') / 'toto.py'
importlib_resources.as_file(toto)
```
