### ISSUE TITLE
Thoughts on the current API

### ISSUE THREAD

**Issue by jaraco** [python/importlib_resources#26]
In GitLab by @warsaw on Nov 13, 2017, 12:27

Over the weekend, I wrote an [experimental branch](https://gitlab.com/mailman/mailman/merge_requests/345/diffs) to switch Mailman 3 to importlib_resources.  Sorry for the catch-all issue, but I want to at least capture my thoughts on the current API.  We can turn these into separate issues if/when we want to change anything.  And at least this should serve as a good conversion guide for #16 .

* `open()` isn't a very good name, especially if you tend to use `from importlib_resources import` style imports.  I do like the shorter name, but the problem is obvious: this shadows the built-in `open()` function.  In my branch, I've used `from importlib_resources import open as resources_open` but that's less than ideal.  As `open()` is also the obvious choice for the function name, I don't yet have a good suggested alternative.

* `path()` returning a `pathlib.Path` is problematic.  It's likely the right thing to do, but it means that conversion requires the liberal use of `str()` wrapping, since much existing code is expecting a concrete `str` object.  Maybe this is better in 3.7 (I only tested with 3.6) for stdlib APIs, but won't help you much for internal project APIs that expect a string.   Interestingly, this tends to be a bit easier if you use an `ExitStack` rather than a `with`-statement.  Compare:

```python
        with path('mailman.testing', 'config-with-instances.pck') as pckpath:
            pckfile = str(pckpath)
```

and

```python
        with ExitStack() as resources:
            pckfile = str(resources.enter_context(
                path('mailman.testing', 'config.pck')))
```

* Returning a context from `path()` is often inconvenient.   Of course, I understand why we have to do that, but ensuring that the context is properly cleaned up can be tricky, and it's certainly much less convenient at times.  I've had to change a few internal APIs to accept an `ExitStack` argument, and then add the `path` context to that, since the resources have to be managed several call frames higher.  E.g.

```python
@public
def use_test_organizational_data(resources):
    # Point the organizational URL to our test data.
    filename = str(resources.enter_context(
        path('mailman.rules.tests.data', 'org_domain.txt')))
    url = 'file:///{}'.format(filename)
    return resources.enter_context(
        configuration('dmarc', org_domain_data_url=url))
```

* Missing API.  I couldn't totally rid myself of `pkg_resources` because there's no current alternative to `resource_isdir()` and `resource_listdir()`.  

* `read()` should support binary reads.  I know we have `open()` for that, but it turns out to be convenient if `read(encoding=None)` returned bytes.  I know we talked about that before, but it's become more obvious when using this in real-world code.   Conversely, it's still a bit inconvenient that `open()` only returns a file opened in binary mode.  Fortunately, there's `email.message_from_binary_file()` where I was previously using `email.message_from_file()`, so it wasn't difficult to fix, but it does mean that converting from `pkg_resources` to `importlib_resources` is less mechanical.

**Comment by jaraco** [comment]
In GitLab by @brettcannon on Nov 14, 2017, 16:19

You shouldn't need to call `str()` on a `Path` object in Python 3.6. All of `os.path` will take a path object and you should use `os.fspath()` when you do need to explicitly convert.

**Comment by jaraco** [comment]
In GitLab by @warsaw on Nov 15, 2017, 15:16

On Nov 15, 2017, at 12:58, Brett Cannon <notifications@github.com> wrote:
> 
> If you're talking about a plug-in system for Python code then you're abusing resource reading.

No, definitely not.  What I’m saying is that my plugin system is one particular use case for isdir() and listdir(), but I could imagine there would be others.  Let’s say you wanted to find all the .eml data files in a test directory, or you wanted to compile all .py files in a directory to check for SyntaxErrors.

**Comment by jaraco** [comment]
In GitLab by @warsaw on Nov 15, 2017, 17:38

> The overarching goal for *me* is to make it easy for a project that is currently using pkg_resources, to switch to importlib_resources and avoid the nasty performance overhead of pkg_resources. 

And just as a little motivation, my first analysis of an internal tool's startup times shows these as the top import time offenders, even without touching any of our internal libraries.  It's no surprise what's at the top!

```
235610 pkg_resources                                                                                                                                 
  65217 site                                                                                                                                          
  17793 pkg_resources._vendor.pyparsing                                                                                                               
  11291 ldap3.protocol.rfc4511                                                                                                                        
   8777 pkg_resources.extern.packaging.requirements                                                                                                   
   8372 pkg_resources.extern.packaging.specifiers                                                                                                     
   7419 six                                                                                                                                           
   7316 lxml.etree                                                                                                                                    
   5812 http.cookiejar                                                                                                                                
   4013 psutil._pslinux                                                                                                                               
   3685 platform                                                                                                                                      
   3313 pkg_resources.extern.packaging.version                                                                                                        
   3239 _hashlib                                                                                                                                      
   3113 ssl                                                                                                                                           
   2880 _collections_abc                                                                                                                              
   2771 ldap3.protocol.novell                                                                                                                         
   2727 socket                                                                                                                                        
   2656 psutil._common                                                                                                                                
   2468 psutil                                                                                                                                        
   2408 ipaddress                                                                                                                                     
   2407 ldap3.core.exceptions                                                                                                                         
   2262 http.cookies                                                                                                                                  
   2243 pyasn1.type.univ                                                                                                                              
   2224 inspect                                                                                                                                       
   2028 contextlib
```

**Comment by jaraco** [comment]
In GitLab by @brettcannon on Nov 15, 2017, 16:56

For the "compile `.py` files" then you already know you're using a file system on disk in order to write the `.pyc` files so you don't need it abstracted away. And if you're not writing the files then why are you needing to read what's in a package post-install for tests?

As for the `.eml` file situation, why are you having files added from outside the code itself? If you keep a list of test files in the code to know how to process them and so you don't have to discover anything. (And before you say, "you shouldn't have to repeat yourself", I have not forgotten who created `__all__` 😉 .)

And that's the key question for me: is it worth complicating the API and going to the extent of defining a read-only VFS interface to support people inserting "files" from outside the project's control? If you're installing this from a wheel then you will know ahead of time what files will be available, so why do we have to support discovery? And if you can insert a "file" post-install then you're on a file system, so why do we need to abstract it away?

Or to help list it out, the current API for getting data is:

1. Open a file for binary reading
2. Read a file as text

What you're now proposing is:

1. Open a file (`pathlib.Path.open()`)
   1. Binary reading
   2. Text reading
2. Read a file
   1. Binary reading (`pathlib.Path.read_bytes()`)
   2. Text reading (`pathlib.Path.read_text()`)
3. List directory contents (`pathlib.Path.iterdir()`)
4. Directory/file testing (`pathlib.Path.is_dir()`; I'm assuming you're not asking for a separate `isfile()`)

One list is 2-3x the size of the other 😉 . At the moment we are replicating `builtins.open()` in a simplified form and a single API from `tempfile` along with our custom `read()`. This would toss in `os.path` into the mix, at which point the question becomes where do we stop? And just because PJE thought it was a good idea doesn't mean we should perpetuate it. 😁 

Also realize that because we currently restrict the path to file names only, `isdir()` conflates the concept of a file system with packages since if you find a "directory" you will need to import it to access the "files" contained within it.

After having written all of this, I think my key question is why do we need to have this abstracted for zip files that are pre-built and thus can be told of their contents ahead of time? Otherwise you're on a file system and you can just do `os.path.exists(module.__file__)` and then know you're working on-disk.

**Comment by jaraco** [comment]
In GitLab by @brettcannon on Nov 16, 2017, 14:47

RE: _"contents() returns an Iterable"_: yep, that was a typo on my part. 😄 

RE: _"although I'd like a little more detail on why you think this can't be Iterable[Path]"_": Directories will not work with `open()` or `path()` (unless you're now saying you don't want to return directories, in which case `is_dir()` isn't necessary since you simply won't know they exist through this API). Plus I personally view `pathlib.Path` objects as representing something where actual manipulation of the path -- e.g. getting the parent -- still leads to a valid path, which is not guaranteed in this instance if you're working with a zip file.

RE: _"I still like read() and our current implementation of it is more than one line of code"_: True, it's more than one line at 5 statements in total. But if we add the string-opening feature that you want for `open()` (which I covered in my proposed API change), the code would become:
```python
def read(package, file_name, encoding='utf-8', errors='strict'):
    with open_resource(package, file_name, encoding=encoding, errors=errors) as file:
        return file.read()
```
So while I will concede 2 > 1, you're also leaving out the tests and documentation in that line count that we will have to maintain. 😉 

RE: _""contents" feels a bit ambiguous"_: Sure, but `children()` is also doesn't feel quite right as you're not returning the children of a package, but what resources a package contains. I actually almost named it `resources()`, but I figured `importlib_resources.resources()` seemed a bit redundant. If you don't think so then let's just go with that name.

And your proposed change for `is_file()` won't work as now you're breaking the API contract that the package controls what resources it contains. Your proposal would suddenly have `children()` accept arbitrary `Path` objects and having to know how to work with them. And conflating packages/modules and files is part of what has led to import having this weird situation where so much is treated as if they are files but are in fact not when they are e.g. contained in a zip file. This was actually one of the reasons we chose to only accept file names instead of relative paths in the beginning. IOW I really do not want to have this API suddenly let people arbitrarily work around packages if they are going to be the anchor point for paths because that's when you get people doing stuff that isn't portable across loaders/storage back-ends.

**Comment by jaraco** [comment]
In GitLab by @warsaw on Nov 15, 2017, 17:18

On Nov 15, 2017, at 16:56, Brett Cannon <notifications@github.com> wrote:
> 
> For the "compile .py files" then you already know you're using a file system on disk in order to write the .pyc files so you don't need it abstracted away.

Not necessarily.  You could just want to test for syntax compatibility.  Besides, it’s just an example.  There can be other reasons why you might want to dynamically determine what files are in a particular directory.

> As for the .eml file situation, why are you having files added from outside the code itself?

I don’t understand the question. ;)  Why assume those files are coming from outside the code?

> If you keep a list of test files in the code to know how to process them and so you don't have to discover anything. (And before you say, "you shouldn't have to repeat yourself", I have not forgotten who created __all__ 😉 .)

And also created @public. #DRY :)

> Or to help list it out, the current API for getting data is:
> 
> 	• Open a file for binary reading
> 	• Read a file as text
> What you're now proposing is:
> 
> 	• Open a file (pathlib.Path.open())
> 		• Binary reading
> 		• Text reading
> 	• Read a file
> 		• Binary reading (pathlib.Path.read_bytes())
> 		• Text reading (pathlib.Path.read_text())
> 	• List directory contents (pathlib.Path.iterdir())
> 	• Directory/file testing (pathlib.Path.is_dir(); I'm assuming you're not asking for a separate isfile())

Let’s take these one at a time, and remember I’m just providing usability feedback based on my experiment of actually trying to use the library for an existing application.  The overarching goal for *me* is to make it easy for a project that is currently using pkg_resources, to switch to importlib_resources and avoid the nasty performance overhead of pkg_resources.  So that’s where the motivation to support resource_isdir() and resource_listdir() comes from, and I acknowledge that there will be parts of the pkg_resources API we absolutely do not want to support (e.g. entrypoints, or anything that requires access to dist-info/egg-info metadata).

> After having written all of this, I think my key question is why do we need to have this abstracted for zip files that are pre-built and thus can be told of their contents ahead of time? Otherwise you're on a file system and you can just do os.path.exists(module.__file__) and then know you're working on-disk.

Because part of the attraction to pkg_resources is that you don’t *have* to know whether your on the file system or in a zip file.  I think that’s an important feature to provide.  The logic of handling the details of that distinction has to live somewhere, and applications are currently offloading that to pkg_resources.  If we don’t support these APIs then either they’ll keep pkg_resources around (and even one import of pkg_resources kills performance for the entire application - but I have a sneaky plan for that!), or they’ll be forced to move that logic into their application.

I’m fairly certain that isdir() isn’t hard to implement for filesystem or zipfiles… at least in Python 3.6 ;)

https://docs.python.org/3/library/zipfile.html#zipfile.ZipInfo.is_dir

**Comment by jaraco** [comment]
In GitLab by @warsaw on Nov 16, 2017, 11:46

> You will also notice I have contents() returning an iterable of str and not pathlib.Path since we can't make guarantees that everything that is returned will be usable by open() or path().

Wouldn't that have to be:

```python
def contents(package) -> typing.Iterable[str]
```

?

"contents" feels a bit ambiguous since it can also mean "the contents of a specific file" as well as "all the items contained within a package".  With your proposed dropping of `read()`, I think that makes the API a bit more confusing.

But I get why you probably don't like `list_dir()` here either.   I'd propose:

```python
def children(package) - typing.Iterable[str]
```

although I'd like a little more detail on why you think this can't be `Iterable[Path]`.  What case are you thinking about where the items returned by `children()` (or whatever) couldn't be passed to `open()` or `path()`?

**Comment by jaraco** [comment]
In GitLab by @warsaw on Nov 16, 2017, 11:53

> You will notice I dropped read() since at this point we've crossed into a read-only VFS interface which means we might as well just stick with the file metaphor and not try to hide it behind a convenience function that saves only a single line of code.

I still like `read()` and our current implementation of it is more than one line of code.  The only change I'd make is to conditionalize the `TextIOWrapper` wrapping on `encoding is not None`, e.g.

```
1 file changed, 4 insertions(+), 2 deletions(-)
importlib_resources/_py3.py | 6 ++++--

modified   importlib_resources/_py3.py
@@ -10,7 +10,7 @@ from importlib.abc import ResourceLoader
 from io import BytesIO, TextIOWrapper
 from pathlib import Path
 from types import ModuleType
-from typing import Iterator, Union
+from typing import AnyStr, Iterator, Union
 from typing import cast
 from typing.io import BinaryIO
 
@@ -78,7 +78,7 @@ def open(package: Package, file_name: FileName) -> BinaryIO:
 
 
 def read(package: Package, file_name: FileName, encoding: str = 'utf-8',
-         errors: str = 'strict') -> str:
+         errors: str = 'strict') -> AnyStr:
     """Return the decoded string of the resource.
 
     The decoding-related arguments have the same semantics as those of
@@ -88,6 +88,8 @@ def read(package: Package, file_name: FileName, encoding: str = 'utf-8',
     package = _get_package(package)
     # Note this is **not** builtins.open()!
     with open(package, file_name) as binary_file:
+        if encoding is None:
+            return binary_file.read()
         # Decoding from io.TextIOWrapper() instead of str.decode() in hopes
         # that the former will be smarter about memory usage.
         text_file = TextIOWrapper(
```

And yes, I know this violates the convention that arguments shouldn't change the return type, but it feels like a reasonable compromise for practicality in this case.

**Comment by jaraco** [comment]
In GitLab by @brettcannon on Nov 14, 2017, 16:29

What are you using `resource_isdir()` for? Either you can import the directory as a package or try opening the resource as a file and get `FileNotFoundError`.

As for `resource_listdir()`, I have always tried to stay away from that as that very squarely makes this defining a virtual file system API. And when you get that far you start to look at replicating `pathlib.PurePath` with some extras for reading.

**Comment by jaraco** [comment]
In GitLab by @warsaw on Nov 16, 2017, 11:56

> And is_dir() is still driving me bonkers because you're basically checking if you can import another package which is a totally different concept and API. So let's just say we're discussing the inclusion of is_file() and make my eye twitch less.

Oh, we definitely don't want a twitchy brettsky! :)

I'm fine with `is_file()` instead of `is_dir()` since that just reverses the logic.  With my proposed name change, then I think this is just something like:

```python
def is_file(path) -> bool:
    return len(children(path)) == 0
```

**Comment by jaraco** [comment]
In GitLab by @warsaw on Nov 16, 2017, 11:18

> Let's say your test suite has a data directory that contains test1.eml and test2.eml. You're asking for an API where you can essentially go {test_file for test_file in contents(pkg) if not is_dir(pkg, test_file)}. What I'm saying is why doesn't your test code just have {'test1.eml', 'test2.eml'} since that can be known ahead of time? The only concrete, must-have-it-supported-in-the-API reason that I can think of for being able to discover what the contents of a directory are is because you literally can't known a-priori what's in the directory between when you packaged your code and the user ran your code.

This is true, but if it's not your code, then you can't know a priori what's in it.  Yet you still might want to extract files/contents.

**Comment by jaraco** [comment]
In GitLab by @warsaw on Nov 29, 2017, 16:25

Responding one at a time, and trimming points we have enough agreement on to address separately.

> On Nov 29, 2017, at 15:56, Brett Cannon <notifications@github.com> wrote:

> 	• path() and having to support the API design of PJE: the only way I can see to support this without totally cringing would be with a function that returned a tuple of a Path and a boolean flag that represented whether the path is temporary or not, that way people can do path, is_temp = i_hate_backwards_compat_for_something_i_did_not_design() and do whatever you feel is appropriate based on is_temp; that would make our appropriate context manager just wrap that lower-level function and do the appropriate thing

What about this:

_atexit_manager = None

def register(context_manager):
    global _atexit_manager
    if _atexit_manager is None:
        _atexit_manager = ExitStack()
        atexit.register(_atexit_manager.close)
    _atexit_manager.enter_context.push(context_manager)
    return context_manager


So a translation of:

    filename = pkg_resources.resource_filename(‘my.package’, ‘resource.dat’)

would be:

    filename = importlib_resources.register(importlib_resources.path(‘my.package’, ‘resource.dat’))

It’s not the prettiest thing in the world, but I also think it will be rarely used.  But in those cases where you *can’t* transform the former into:

    with importlib_resources.path(‘my.package’, ‘resource.dat’):

it will be very handy.

I’m also okay with punting on this and including the above as a suggestion in the porting guide I am going to write.

**Comment by jaraco** [comment]
In GitLab by @warsaw on Nov 14, 2017, 16:25

Unfortunately, I have to support Python 3.5, so I can't use `os.fspath()`, or count on `os.path` APIs accepting `Path` objects.  I also have to interface with other APIs that require a string, such as when building up arguments for essentially a subprocess call, passing to click, or using internal APIs which require a string path.

**Comment by jaraco** [comment]
In GitLab by @warsaw on Nov 29, 2017, 11:50

Before I summarize each point brought up here, let me just make a meta-point.  I *really* want to make it easy for existing users of `pkg_resources` to adopt `importlib_resources`.  To the extent that we can write a compatible API (even if the names are different) that makes that easy and/or mechanical, I'm all for it.  If I need to write yet another package that provides a compatibility shim, then I'll do that.

Of course, we have to balance that against doing what's right for importlib_resources, especially since we intend this to be added to the stdlib and we don't want to incur too much tech debt right off the bat.

We probably won't get this right no matter what we do because we won't know for sure until it gets more widespread use, both as a 3rd party module and in the stdlib.  But I don't want to push this off until 3.8 so I propose that we make whatever API we end up with explicitly *provisional* in 3.7.

* Drop `read()`.  I would still like to keep `read()` even as a convenience because that maps directly onto `resource_string()` (which in Python 3 actually returns bytes).  That's why I want to support `encoding=None` for binary reads.  That gives us a nice mechanical transformation from `resource_string()` to `read(encoding=None)`.  I don't think the maintenance burden or conceptual jujitsu is that terrible.

* Extend `open()` to include `encoding` and `error` parameters.  I'm okay with this *if* `encoding=None` by default for binary opens.  This maps directly onto `resource_stream()`.  

* Rename `open()`.  I still don't like `open()` because of the name clash with built-in `open()`, but we do have precedence with `codecs.open()` although that's shorter than `importlib.resources.open()` (and less useful in Python 3).  The only thing I can come up with as an alternative is `stream()` harkening back to `resource_stream()` but that's also not great, so if we must keep the name `open()`, so be it.  Maybe we'll get more useful feedback once other people start to use it.

* `def resources(package) -> Iterable[str]` or `def contents(package) -> Iterable[str]`.  You don't like `children()` and I concur with you on `importlib.resources.resources()`.  The closest analogy I can find is `Path.iterdir()` but... yuck :).   `importlib.resources.iterpackage()`?    I want this functionality, so I'm okay with whatever name you choose. :)

* `def is_file(package, file_name) -> bool` - works for me!

* `path()` returning a context.  I still think this can be a problem as a pkg_resources replacement, but it *is* the right API.  Somewhere there should be a shim to map onto `pkg_resources.resource_filename()` which would do the cleanup in an `atexit` handler.  I'm okay with that shim not being in importlib_resources, though it would be convenient.  One terrible possibility would be to add an optional `contextmgr` argument to `path()` defaulting to None.  The default would have the current behavior, while non-None would add the context to the passed in context manager.  That way users can set up their own `atexit` handler and the conversion from `resource_filename()` would be easier.  If we don't do anything about this, our documentation should give suggestions for this migration because it can't be done mechanically.

I think that covers all the points.  Eager to hear your feedback.  I think we should soon turn each one of these API questions into separate issues, and I'm willing to do that.

**Comment by jaraco** [comment]
In GitLab by @brettcannon on Nov 15, 2017, 12:58

If you're talking about a plug-in system for Python code then you're abusing resource reading. 😉 If that's what you're using it for then what you want is me to have enough time to develop an API for finders which will return an iterable of known modules the finder can create a loader for.

**Comment by jaraco** [comment]
In GitLab by @brettcannon on Nov 29, 2017, 15:56

* You can keep `read()`, I'm just assigning all bugs related to it to you 😁 
* `open()` returning potentially strings is fine by me
* Renaming `open()` is fine, but I don't have a good suggestion
* The naming of `contents()`; no good answer either, but a clarification question below which might help with this
* `is_file()` name is fine, although read below for a clarification of whether this is needed/desired or there's a better name in `is_resource()`
* `path()` and having to support the API design of PJE: the only way I can see to support this without totally cringing would be with a function that returned a tuple of a Path and a boolean flag that represented whether the path is temporary or not, that way people can do `path, is_temp = i_hate_backwards_compat_for_something_i_did_not_design()` and do whatever you feel is appropriate based on `is_temp`; that would make our appropriate context manager just wrap that lower-level function and do the appropriate thing

So my clarification question is what do you want `contents()` to return? Is it meant to be file names only, or do you explicitly want directories as well? I ask because the former should be readable by the API while the latter won't be and it will be some wonky "it's a directory that you can't actually directly access through this API, but we expect you to treat it like a package and import it to squeeze it in". If it were just file names that can be read with `importlib_resources` then we can drop `is_file()` and the API doesn't conflate as much with file names & directories and stays a package & resources thing.

If **you** do want directories to also be listed, then `is_file()` is leaking out a common detail through its name, so maybe `is_resource()` is a better name? In which case you're LBYL for whether a file name will work.

**Comment by jaraco** [comment]
In GitLab by @warsaw on Nov 14, 2017, 19:54

We use `resource_isdir()` in the plugin system.  A plugin can have any of a number of subdirectories, corresponding to the components that the plugin optionally provides.  We discover these dynamically, using this API.  `resource_listdir()` then is used to find all the modules inside such a directory.

I think both could be supported without fully going down the virtual filesystem path.  I don't know if it's a good idea, but it could be done.  The real trick is mapping that functionality onto both the filesystem and the zipfile format in a compatible way (e.g. [ZipInfo.is_dir()](https://docs.python.org/3/library/zipfile.html#zipfile.ZipInfo.is_dir) though sadly only for Python 3.6), through a generic API that makes sense for `importlib_resources`.  `pkg_resources` probably gets away with it by unpacking to a directory (I don't actually know).

I'll have to keep thinking about this one.  I want to be able to ditch `pkg_resources` entirely!

**Comment by jaraco** [comment]
In GitLab by @warsaw on Nov 29, 2017, 17:00

> 	• The naming of contents(); no good answer either, but a clarification question below which might help with this
> 	• is_file() name is fine, although read below for a clarification of whether this is needed/desired or there's a better name in is_resource()
> 
> So my clarification question is what do you want contents() to return? Is it meant to be file names only, or do you explicitly want directories as well? I ask because the former should be readable by the API while the latter won't be and it will be some wonky "it's a directory that you can't actually directly access through this API, but we expect you to treat it like a package and import it to squeeze it in". If it were just file names that can be read with importlib_resources then we can drop is_file() and the API doesn't conflate as much with file names & directories and stays a package & resources thing.
> 
> If you do want directories to also be listed, then is_file() is leaking out a common detail through its name, so maybe is_resource() is a better name? In which case you're LBYL for whether a file name will work.

Let’s start by seeing what happens today if you give a directory as the filename argument to say, `open()`:

```
Python 3.6.3 (default, Oct  4 2017, 06:09:15) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from importlib_resources import open
>>> with open('importlib_resources', 'tests') as fp:
...   fp.read()
... 
Traceback (most recent call last):
  File "/Users/barry/projects/implib/trunk/importlib_resources/_py3.py", line 63, in open
    return builtins_open(full_path, 'rb')
IsADirectoryError: [Errno 21] Is a directory: '/Users/barry/projects/implib/trunk/importlib_resources/tests'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/barry/projects/implib/trunk/importlib_resources/_py3.py", line 70, in open
    data = loader.get_data(full_path)
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
IsADirectoryError: [Errno 21] Is a directory: '/Users/barry/projects/implib/trunk/importlib_resources/tests'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/barry/projects/implib/trunk/importlib_resources/_py3.py", line 75, in open
    raise FileNotFoundError(message)
FileNotFoundError: 'tests' resource not found in ‘importlib_resources'
```

So the question is whether `is_resource(‘importlib_resources’, ‘tests’)` would return True or False?  I would say that the sensible answer for consistency would have to be False.  Directories are not resources within a package.

But if we want an equivalent to `pkg_resources.listdir()` then it would have to return `tests` in the list even though it’s not a resource.  So this method **can’t** be called `importlib_resources.resources()`.  I think that logically leads to:

```python
def contents(package: Package) -> Iterator[str]
```

and I can’t think of a better name than `contents()`.

This means `contents()` does not (necessarily) return resources!  You cannot pass every element of `contents()` to e.g. `open()` without checking whether it’s a resource.  So that means you’d have to do the following migrations:

from:

```python
for entry in pkg_resources.resource_listdir(package, ''):
```

to:

```python
for entry in importlib_resources.contents(package):
```

and

```python
if pkg_resources.isdir(package, entry):
```

to

```python
entry in contents(package) and not is_resource(package, entry)
```

The latter is a bit ugly, but I can live with it.

**Comment by jaraco** [comment]
In GitLab by @brettcannon on Nov 30, 2017, 14:27

🎉 for compromise! 😉 

I think we need to be very clear in the documentation for `contents()` and its equivalent loader API that it's expected to return resources that can be read and optionally directories which may or may not be importable.

**Comment by jaraco** [comment]
In GitLab by @brettcannon on Nov 29, 2017, 16:33

I'm not feeling it as I feel like we just wrote something for contextlib. I say we punt for now and have an example in the docs instead.

**Comment by jaraco** [comment]
In GitLab by @brettcannon on Nov 15, 2017, 17:48

RE: "I don’t understand the question. ;) Why assume those files are coming from outside the code?"

Let's say your test suite has a data directory that contains `test1.eml` and `test2.eml`. You're asking for an API where you can essentially go `{test_file for test_file in contents(pkg) if not is_dir(pkg, test_file)}`. What I'm saying is why doesn't your test code just have `{'test1.eml', 'test2.eml'}` since that can be known ahead of time? The only concrete, must-have-it-supported-in-the-API reason that I can think of for being able to discover what the contents of a directory are is because you literally can't known a-priori what's in the directory between when you packaged your code and the user ran your code. This is why this is turning out to be a "simple is better than complex"/"practicality beats purity" argument.

And `is_dir()` is still driving me bonkers because you're basically checking if you can import another package which is a totally different concept and API. So let's just say we're discussing the inclusion of `is_file()` and make my eye twitch less. 😄 

[sigh]

OK, so let's put this into concrete terms. You're basically proposing the following ABC be implemented by loaders:
```python
class ResourceReader(abc.ABC):
    def open_resource(file_name: str) -> BinaryIO:
        ...

    def resource_path(file_name: str) -> str:
        ...

    def resources() -> Iterable[str]:
        ...

    def resource_is_file() -> bool:
        ...
```

I would then argue the API we would provide is:
```python
def open(package, file_name, encoding, errors) -> typing.IO:
    ...

@contextlib.contextmanager
def path(package, file_name) -> typing.Iterable[pathlib.Path]:
    ...

def resources(package) -> Iterable[str]:
    ...

def is_file(package, file_name) -> bool:
    ...
```

You will notice I dropped `read()` since at this point we've crossed into a read-only VFS interface which means we might as well just stick with the file metaphor and not try to hide it behind a convenience function that saves only a single line of code. You will also notice I have `contents()` returning an iterable of `str` and not `pathlib.Path` since we can't make guarantees that everything that is returned will be usable by `open()` or `path()`. Plus chances are the results will just be passed directly into either of those functions as filtered by `is_file()` anyway, so no need to add an extra level of stuff on top of it.

Does this compromise make the FLUFL happy? 😉

**Comment by jaraco** [comment]
In GitLab by @warsaw on Nov 30, 2017, 14:37

For sure, and sounds great!  I'll start pushing some PRs.  Maybe we can do a PyPI release early next week (time's running out for Python 3.7!)

**Comment by jaraco** [comment]
In GitLab by @brettcannon on Nov 30, 2017, 17:23

That's fine. I should be available enough to do reviews, it's just a question of content generation time.

**Comment by jaraco** [comment]
In GitLab by @brettcannon on Nov 30, 2017, 15:02

I'm also in the process of buying a townhouse and planning a move so don't be shocked if my availability isn't great through the rest of December.

**Comment by jaraco** [comment]
In GitLab by @warsaw on Nov 30, 2017, 16:33

Good luck and no worries!  I'm happy to do the bulk of the work, though I'll need to you review in order to unblock PRs.

**Comment by jaraco** [comment]
In GitLab by @warsaw on Dec 1, 2017, 20:15

I'm closing this issue now.  All outstanding API concerns have been addressed, and are either file as separate issues or submitted as PRs.
