### ISSUE TITLE
read_text() of a zip file package doesn't find a resource

### ISSUE THREAD

**Issue by jaraco** [python/importlib_resources#48]
In GitLab by @encukou on Dec 21, 2017, 10:03

Hi,

In issue #44 I reported a problem with `importlib_resources.contents()` and `importlib_resources.read()`, but then the the bug title was changed, and only the first of those was fixed. Sorry if I wasn't clear enough that it wasn't just `contents()`.

The remaining problem is, `importlib_resources.read_text()` (and probably similar functions) fails to find resources in zip archives.

Here is reproducer -- run on a *nix, in an empty directory, with importlib_resources installed:

```bash
#! /bin/bash -ex

# Preparation
rm -rf demo.pyz demo
mkdir -p demo/demo

# Populate files to be packaged
echo "
import importlib_resources

def main():
    for resource in importlib_resources.contents(__name__):
        if resource.endswith('.txt'):
            print('Reading:', resource)
            text = importlib_resources.read_text(__name__, resource)
            print('Length:', len(text))
" > demo/demo/__init__.py

echo "This is a resource" > demo/demo/resource.txt

# Zip everything up
python -m zipapp demo -o demo.pyz -m demo:main

# Try to run it
python --version
python demo.pyz
```

Result:

```pycon
Reading: resource.txt
Traceback (most recent call last):
  File "/tmp/fghj/__venv__/lib64/python3.6/site-packages/importlib_resources/_py3.py", line 111, in open_text
    full_path, mode='r', encoding=encoding, errors=errors)
NotADirectoryError: [Errno 20] Not a directory: '/tmp/demo.pyz/demo/resource.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "demo.pyz/__main__.py", line 3, in <module>
  File "demo.pyz/demo/__init__.py", line 8, in main
  File "__venv__/lib64/python3.6/site-packages/importlib_resources/_py3.py", line 149, in read_text
    with open_text(package, resource, encoding, errors) as fp:
  File "__venv__/lib64/python3.6/site-packages/importlib_resources/_py3.py", line 125, in open_text
    raise FileNotFoundError(message)
FileNotFoundError: 'resource.txt' resource not found in 'demo'
```

Expected result (what I get when I use `pkg_resources` by “anti-following” the Migration Guide):

```
Reading: resource.txt
Length: 19
```

**Comment by jaraco** [comment]
In GitLab by @warsaw on Jan 2, 2018, 15:19

assigned to @warsaw

**Comment by jaraco** [comment]
In GitLab by @warsaw on Jan 2, 2018, 15:20

Thanks @encukou - I didn't realize this affected other functions.

**Comment by jaraco** [comment]
In GitLab by @warsaw on Feb 15, 2018, 22:28

Confirmed!  This isn't a problem with Python 3.7.

**Comment by jaraco** [comment]
In GitLab by @warsaw on Feb 17, 2018, 21:45

I'm punting this one back to Python.  If you change the last line to:

```
python `pwd`/demo.pyz
```

then it works as expected.  I believe this comes down to zipimporter's loader's `get_data()` not being able to find `pathname` when the zip file's path is relative.  AFAICT this isn't a known issue upstream; I'll open a bug on Python, but mark this as Won't Fix here.

**Comment by jaraco** [comment]
In GitLab by @warsaw on Feb 17, 2018, 21:49

https://bugs.python.org/issue32866

**Comment by jaraco** [comment]
In GitLab by @warsaw on Feb 17, 2018, 21:49

closed

**Comment by jaraco** [comment]
In GitLab by @warsaw on Feb 17, 2018, 22:03

removed milestone

**Comment by jaraco** [comment]
In GitLab by @warsaw on Jan 17, 2019, 13:41

FYI, I believe both relative and absolute paths will work in Python 3.8 where zipimport is rewritten in Python.  See the upstream bug for details.
