### ISSUE TITLE
Cannot use with PyInstaller

### ISSUE THREAD

**Issue by jaraco** [python/importlib_resources#62]
In GitLab by @pacm on Jun 11, 2018, 03:22

Hi! I tried to freeze my application, which uses importlib_resources, with pyinstaller. However, I get the following problem:
```
Traceback (most recent call last):
  File "site-packages/importlib_resources/_py3.py", line 120, in open_text
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEIo5mCFb/importlib_resources/version.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "execs/factory-base.py", line 1, in <module>
    from cactus_factory.desktop import run_app
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/pacm/.local/share/virtualenvs/factory-xSiE1XGz/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 628, in exec_module
    exec(bytecode, module.__dict__)
  File "cactus_factory/desktop.py", line 6, in <module>
    from cactus_factory.web import server
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/pacm/.local/share/virtualenvs/factory-xSiE1XGz/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 628, in exec_module
    exec(bytecode, module.__dict__)
  File "cactus_factory/web/server.py", line 8, in <module>
    from cactus_factory.web.views.factory import factory_view
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/pacm/.local/share/virtualenvs/factory-xSiE1XGz/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 628, in exec_module
    exec(bytecode, module.__dict__)
  File "cactus_factory/web/views/factory.py", line 12, in <module>
    from cactus_factory.toolset import Toolset
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/pacm/.local/share/virtualenvs/factory-xSiE1XGz/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 628, in exec_module
    exec(bytecode, module.__dict__)
  File "cactus_factory/toolset.py", line 7, in <module>
    from cactus_factory import log, printer
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/pacm/.local/share/virtualenvs/factory-xSiE1XGz/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 628, in exec_module
    exec(bytecode, module.__dict__)
  File "cactus_factory/printer.py", line 10, in <module>
    import importlib_resources
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/pacm/.local/share/virtualenvs/factory-xSiE1XGz/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 628, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/importlib_resources/__init__.py", line 36, in <module>
  File "site-packages/importlib_resources/_py3.py", line 158, in read_text
  File "site-packages/importlib_resources/_py3.py", line 134, in open_text
FileNotFoundError: 'version.txt' resource not found in 'importlib_resources'
[20958] Failed to execute script factory-base
```

I am using python 3.6.5, Ubuntu 18.04 LTS

**Comment by jaraco** [comment]
In GitLab by @warsaw on Jun 28, 2018, 13:06

Is it possible that pyinstaller doesn't include the `.txt` file?  It works for me in a virtualenv:

```
% python3 -m venv /tmp/vv
% source /tmp/vv/bin/activate
(vv) % pip install importlib_resources
Collecting importlib_resources
  Downloading https://files.pythonhosted.org/packages/a9/41/91dafab685a23df2a5e49122b9207701f0320b6b0802b0685bf5bb4b9d6a/importlib_resources-0.8-py2.py3-none-any.whl
Collecting wheel (from importlib_resources)
  Using cached https://files.pythonhosted.org/packages/81/30/e935244ca6165187ae8be876b6316ae201b71485538ffac1d718843025a9/wheel-0.31.1-py2.py3-none-any.whl
Requirement already satisfied: setuptools in /private/tmp/vv/lib/python3.7/site-packages (from importlib_resources) (39.0.1)
Installing collected packages: wheel, importlib-resources
Successfully installed importlib-resources-0.8 wheel-0.31.1
(vv) % python
Python 3.7.0rc1+ (heads/3.7:6bb7704451, Jun 17 2018, 11:32:36) 
[Clang 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import importlib_resources
>>> importlib_resources.__version__
'0.8'
>>> ^D
```

**Comment by jaraco** [comment]
In GitLab by @pacm on Jul 3, 2018, 04:13

virtualenv also works for me, I will investigate how properly add the `.txt` file to pyinstaller.

**Comment by jaraco** [comment]
In GitLab by @pacm on Jul 4, 2018, 17:23

In the end, I needed to add
```python
datas=[('version.txt', 'importlib_resources')]
```
to the spec file. I hope PyInstaller is able to figure out resources specified by importlib_resources in the future.

**Comment by jaraco** [comment]
In GitLab by @pacm on Jul 4, 2018, 17:23

closed
