### ISSUE TITLE
Publish a wheel to pypi?

### ISSUE THREAD

**Issue by jaraco** [python/importlib_resources#67]
In GitLab by @asottile on Oct 23, 2018, 19:12

https://pypi.org/simple/importlib-resources/

Seems to be missing wheels for newer versions

**Comment by jaraco** [comment]
In GitLab by @warsaw on Oct 25, 2018, 13:49

Sure, happy to publish wheels too.

**Comment by jaraco** [comment]
In GitLab by @warsaw on Oct 25, 2018, 13:49

assigned to @warsaw

**Comment by jaraco** [comment]
In GitLab by @asottile on Oct 25, 2018, 14:17

This could even be done with the current release by (something like this):

```bash
pip wheel --no-cache --no-deps importlib-resources
twine upload -r pypi *.whl
```

(need to make sure you're in an environment with latest pip + latest setuptools though, old setuptools produces a broken wheel due to some metadata oddity?)

**Comment by jaraco** [comment]
In GitLab by @jaraco on Oct 29, 2018, 21:07

For this project (because it uses declarative config), it's more than a convenience to supply wheels; it's a necessity to support installation on pip older than 10 and setuptools older than 30.3:

```
~ $ rwt 'pip<10' 'setuptools<30.3' -- -m rwt --no-cache importlib_resources -- -c "import importlib_resources"
Collecting pip<10
  Using cached https://files.pythonhosted.org/packages/ac/95/a05b56bb975efa78d3557efa36acaf9cf5d2fd0ee0062060493687432e03/pip-9.0.3-py2.py3-none-any.whl
Collecting setuptools<30.3
  Using cached https://files.pythonhosted.org/packages/05/c3/b5534ca0113d5a6779802644f88f9e110de92287d2d11b7f83723778c83c/setuptools-30.2.1-py2.py3-none-any.whl
Installing collected packages: pip, setuptools
pipenv 2018.7.1 has requirement setuptools>=36.2.1, but you'll have setuptools 30.2.1 which is incompatible.
Successfully installed pip-9.0.3 setuptools-30.2.1
Collecting importlib_resources
  Downloading https://files.pythonhosted.org/packages/d2/09/1f4148ee5ec0022d122bb9a94428a70f858863d47df573dd8c382fa8f1c2/importlib_resources-1.0.1.tar.gz
Installing collected packages: unknown
  Running setup.py (path:/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-build-z5v0sans/importlib-resources/setup.py) egg_info for package importlib-resources produced metadata for project name unknown. Fix your #egg=importlib-resources fragments.
  Running setup.py install for unknown ... done
Successfully installed unknown-0.0.0
You are using pip version 9.0.3, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'importlib_resources'
```

**Comment by jaraco** [comment]
In GitLab by @warsaw on Nov 1, 2018, 13:43

I just [uploaded the whl for 1.0.1](https://pypi.org/project/importlib_resources/#files).  Please test it and let me know!  I'll be sure to upload both the wheel and the sdist in the future.

**Comment by jaraco** [comment]
In GitLab by @warsaw on Nov 1, 2018, 13:43

closed

**Comment by jaraco** [comment]
In GitLab by @asottile on Nov 1, 2018, 13:49

Looks great, even works with pip 1.5:

```console
$ pip install 'pip<6' --upgrade
Collecting pip<6
  Downloading https://files.pythonhosted.org/packages/3f/08/7347ca4021e7fe0f1ab8f93cbc7d2a7a7350012300ad0e0227d55625e2b8/pip-1.5.6-py2.py3-none-any.whl (1.0MB)
    100% |████████████████████████████████| 1.0MB 5.7MB/s 
Installing collected packages: pip
  Found existing installation: pip 18.1
    Uninstalling pip-18.1:
      Successfully uninstalled pip-18.1
Successfully installed pip-1.5.6

$ pip install importlib-resources
Downloading/unpacking importlib-resources
  Downloading importlib_resources-1.0.1-py2.py3-none-any.whl
Downloading/unpacking pathlib2 (from importlib-resources)
  Downloading pathlib2-2.3.2-py2.py3-none-any.whl
Downloading/unpacking typing (from importlib-resources)
  Downloading typing-3.6.6-py2-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): wheel in ./venv/lib/python2.7/site-packages (from importlib-resources)
Requirement already satisfied (use --upgrade to upgrade): setuptools in ./venv/lib/python2.7/site-packages (from importlib-resources)
Downloading/unpacking scandir (from pathlib2->importlib-resources)
  Downloading scandir-1.9.0.tar.gz
  Running setup.py (path:/tmp/venv/build/scandir/setup.py) egg_info for package scandir
    /usr/lib/python2.7/distutils/extension.py:133: UserWarning: Unknown Extension options: 'optional'
      warnings.warn(msg)
Downloading/unpacking six (from pathlib2->importlib-resources)
  Downloading six-1.11.0-py2.py3-none-any.whl
Installing collected packages: importlib-resources, pathlib2, typing, scandir, six
Compiling /tmp/venv/build/importlib-resources/importlib_resources/_py3.py ...
  File "/tmp/venv/build/importlib-resources/importlib_resources/_py3.py", line 25
    def _get_package(package) -> ModuleType:
                              ^
SyntaxError: invalid syntax

  Running setup.py install for scandir
    /usr/lib/python2.7/distutils/extension.py:133: UserWarning: Unknown Extension options: 'optional'
      warnings.warn(msg)
    building '_scandir' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-nbjU53/python2.7-2.7.15~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c _scandir.c -o build/temp.linux-x86_64-2.7/_scandir.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-nbjU53/python2.7-2.7.15~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-nbjU53/python2.7-2.7.15~rc1=. -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/_scandir.o -o build/lib.linux-x86_64-2.7/_scandir.so
  Could not find .egg-info directory in install record for scandir (from pathlib2->importlib-resources)
Successfully installed importlib-resources pathlib2 typing scandir six
Cleaning up...

$ python
Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import importlib_resources

```

**Comment by jaraco** [comment]
In GitLab by @ntrepid8 on Nov 1, 2018, 16:15

Something I've noticed is that it seems like multiple iterations of the wheel file have been uploaded for:
```
importlib-resources==1.0.1
```

I am seeing a security warning when using [pipenv](https://github.com/pypa/pipenv) to install packages because the downloaded artifact is hashed and compared to the original hash calculated when the package was first installed.

```
$ pipenv install
Installing dependencies from Pipfile.lock

(snipped...)

THESE PACKAGES DO NOT MATCH THE HASHES FROM Pipfile.lock!. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    importlib-resources==1.0.1 from https://files.pythonhosted.org/packages/81/a3/466b268701207e00b4440803be132e892bd9fc74f1fe786d7e33146ad2c7/importlib_resources-1.0.1-py2.py3-none-any.whl#sha256=87684c76eca1c1b76012a6771be451b2aadc549dbe2725d17ab6398d39878a33 (from -r /tmp/pipenv-7B4nS3-requirements/pipenv-bURCzt-requirement.txt (line 1)):
        Expected sha256 73f454e062ac149bafd262b18c1f9ebc91f53bd6474e028d1bf1c59ebd152efb
             Got        87684c76eca1c1b76012a6771be451b2aadc549dbe2725d17ab6398d39878a33
```

Is it possible that the wheel was rebuilt and uploaded more than once for version 1.0.1?

**Comment by jaraco** [comment]
In GitLab by @asottile on Nov 1, 2018, 17:28

the expected sha256 is that of the sdist -- you probably just raced with lock creation and wheel upload.  pipenv+-

**Comment by jaraco** [comment]
In GitLab by @warsaw on Nov 1, 2018, 17:41

I'm pretty sure PyPI prevents double uploads for the same version.  I did just upload 1.0.2 (both sdist and wheel) shortly after uploading the wheel for 1.0.1.
