### ISSUE TITLE
Test failure due to loading a Python 2 only module

### ISSUE THREAD

**Issue by jaraco** [python/importlib_resources#69]
In GitLab by @FRidh on Nov 21, 2018, 06:15

The following happens when running the unit tests with Python 3. I doubt the `_py2.py` module should be loaded.
```py
_py2 (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: _py2 (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: _py2
Traceback (most recent call last):
  File "/nix/store/ilrzz576hxzzajnkdr6p452zs0qm5qzm-python3-3.6.7/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/build/importlib_resources-1.0.2/importlib_resources/_py2.py", line 9, in <module>
    from pathlib2 import Path
ModuleNotFoundError: No module named 'pathlib2'
```

**Comment by jaraco** [comment]
In GitLab by @FRidh on Nov 21, 2018, 06:15

changed the description

**Comment by jaraco** [comment]
In GitLab by @FRidh on Nov 21, 2018, 06:16

changed the description

**Comment by jaraco** [comment]
In GitLab by @jaraco on Dec 26, 2018, 19:56

I'm not able to replicate the error, and the error doesn't happen in the GitLab pipelines. You'll need to provide more information and ascertain why tests are failing when you run them but not when they're run in GitLab.

**Comment by jaraco** [comment]
In GitLab by @FRidh on Dec 27, 2018, 03:22

We invoked tests using
```
python setup.py tests
```
Invoking instead
```
python -m unittest discover
```
solved it.

I recall now it happens more often that unittest imports files to search for files while it should not.

**Comment by jaraco** [comment]
In GitLab by @FRidh on Dec 27, 2018, 03:22

closed
