### ISSUE TITLE
Import problem under Pythonista

### ISSUE THREAD

**Issue by jaraco** [python/importlib_resources#94]
In GitLab by @jmmelko on May 6, 2020, 08:02

Hi there,

Your module is very precious to me, but unfortunately I cannot get it to run under Pythonista (Python 3.6.1), for iOS (13.4.1).

This is an import problem. I know that Pythonista is not 100% standard because, for instance, os.getenv('LANG') returns None.
But all my other modules work (including fancy modules such as pillow, mido, etc).

I could not solve it myself because you are using a very elaborate mechanism to import modules and distributions (objects creating objects that create iterable objects that....)

Please tell me what I can test to help you further.

Here is the error log:

```
Traceback (most recent call last):
  File "/private/var/mobile/Library/Mobile Documents/iCloud~com~omz-software~Pythonista3/Documents/sky-python-music-sheet-maker/src/skymusic/resources/Resources.py", line 3, in <module>
    from importlib import resources as importlib_resources
ImportError: cannot import name 'resources'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/5865FE85-BBF0-4610-9517-47716CEAB959/Pythonista3/Documents/site-packages-3/importlib_resources/_compat.py", line 39, in <module>
    from importlib import metadata
ImportError: cannot import name 'metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/var/mobile/Library/Mobile Documents/iCloud~com~omz-software~Pythonista3/Documents/sky-python-music-sheet-maker/src/skymusic/command_line_player.py", line 9, in <module>
    from src.skymusic.music_sheet_maker import MusicSheetMaker
  File "/private/var/mobile/Library/Mobile Documents/iCloud~com~omz-software~Pythonista3/Documents/sky-python-music-sheet-maker/src/skymusic/music_sheet_maker.py", line 4, in <module>
    from src.skymusic.parsers.song_parser import SongParser
  File "/private/var/mobile/Library/Mobile Documents/iCloud~com~omz-software~Pythonista3/Documents/sky-python-music-sheet-maker/src/skymusic/parsers/song_parser.py", line 6, in <module>
    from src.skymusic import instruments, Lang
  File "/private/var/mobile/Library/Mobile Documents/iCloud~com~omz-software~Pythonista3/Documents/sky-python-music-sheet-maker/src/skymusic/instruments.py", line 3, in <module>
    from src.skymusic import notes
  File "/private/var/mobile/Library/Mobile Documents/iCloud~com~omz-software~Pythonista3/Documents/sky-python-music-sheet-maker/src/skymusic/notes.py", line 2, in <module>
    from src.skymusic.resources import Resources
  File "/private/var/mobile/Library/Mobile Documents/iCloud~com~omz-software~Pythonista3/Documents/sky-python-music-sheet-maker/src/skymusic/resources/Resources.py", line 5, in <module>
    import importlib_resources
  File "/private/var/mobile/Containers/Shared/AppGroup/5865FE85-BBF0-4610-9517-47716CEAB959/Pythonista3/Documents/site-packages-3/importlib_resources/__init__.py", line 5, in <module>
    from ._compat import metadata
  File "/private/var/mobile/Containers/Shared/AppGroup/5865FE85-BBF0-4610-9517-47716CEAB959/Pythonista3/Documents/site-packages-3/importlib_resources/_compat.py", line 41, in <module>
    import importlib_metadata as metadata  # type: ignore
  File "/private/var/mobile/Containers/Shared/AppGroup/5865FE85-BBF0-4610-9517-47716CEAB959/Pythonista3/Documents/site-packages-3/importlib_metadata/__init__.py", line 602, in <module>
    __version__ = version(__name__)
  File "/private/var/mobile/Containers/Shared/AppGroup/5865FE85-BBF0-4610-9517-47716CEAB959/Pythonista3/Documents/site-packages-3/importlib_metadata/__init__.py", line 564, in version
    return distribution(distribution_name).version
  File "/private/var/mobile/Containers/Shared/AppGroup/5865FE85-BBF0-4610-9517-47716CEAB959/Pythonista3/Documents/site-packages-3/importlib_metadata/__init__.py", line 537, in distribution
    return Distribution.from_name(distribution_name)
  File "/private/var/mobile/Containers/Shared/AppGroup/5865FE85-BBF0-4610-9517-47716CEAB959/Pythonista3/Documents/site-packages-3/importlib_metadata/__init__.py", line 205, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: importlib_metadata
```

**Comment by jaraco** [comment]
In GitLab by @jmmelko on May 6, 2020, 08:02

changed the description

**Comment by jaraco** [comment]
In GitLab by @jmmelko on May 6, 2020, 08:03

changed the description

**Comment by jaraco** [comment]
In GitLab by @jmmelko on May 6, 2020, 08:10

changed the description

**Comment by jaraco** [comment]
In GitLab by @jmmelko on May 6, 2020, 12:11

Actually what is very strange is that I just need to override the \_\_version\_\_ = lines in \_\_init\_\_.py, by setting a dummy version tuple, and the module works as expected.

**Comment by jaraco** [comment]
In GitLab by @jmmelko on May 6, 2020, 13:15

Ok that was because the .dist-info folder was not installed by stash-pip.

I have created an issue at the Stash repository.

In any case it would be cool if you could add an error message such as “no dist-info or .egg file found. Please check your installation”.
I am not an expert, but I find it odd that a package should rely on a companion folder to run. I don’t find it very safe, even more if it’s only to get the version number...

Thank you.

**Comment by jaraco** [comment]
In GitLab by @jaraco on Jun 13, 2020, 12:38

> I have created an issue at the Stash repository.

Would you mind linking to that issue?

> it would be cool if you could add an error message such as “no dist-info or .egg file found. Please check your installation”.

I agree. That issue would apply to importlib_metadata and not importlib_resources. Can you file the issue with [that project](/python-devs/importlib_resources)?

**Comment by jaraco** [comment]
In GitLab by @jmmelko on Jun 13, 2020, 14:42

Hi,

The issue in the stash repository is here:
https://github.com/ywangd/stash/issues/411

Sorry, I didn’t know that importlib_metadata and resources were two very different things.

I have reported the issue here:
https://gitlab.com/python-devs/importlib_metadata/-/issues/124

**Comment by jaraco** [comment]
In GitLab by @jaraco on Jun 14, 2020, 12:16

Thanks. In addition to addressing concerns there, in #100, I've proposed to remove `__version__` which will suppress the failure and mask the underlying problem. There's no more to do on this issue here.

**Comment by jaraco** [comment]
In GitLab by @jaraco on Jun 14, 2020, 12:16

closed
